### ISSUE TITLE
Money back!!!

### ISSUE THREAD

**Issue by mandulaj** [rifkatz/speedreading#2]
I would like to have a full refund by tomorrow. This project is not working... I love the design but the content is rubbish, DO NOT USE!!!!

**Comment by arselzer** [comment]
:smiley: haha, I just got an email and wondered what was going on

**Comment by mandulaj** [comment]
:smile:

**Comment by rifkatz** [comment]
Hey :( !

**Comment by mandulaj** [comment]
I am outahere...

**Comment by mandulaj** [comment]
Btw, @rifkatz, you should use GitHub more often...

**Comment by arselzer** [comment]
@zpiman  :+1: agreed :smiley:
